version: "3"
services:
  pathfinder:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pathfinder
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - CHAIN_ID=`${CHAIN_ID}`
      - FEEDER_GATEWAY_URL=`${FEEDER_GATEWAY_URL}`
      - GATEWAY_URL=`${GATEWAY_URL}`
    env_file:
      - .env
    ports:
      - "9545:9545"
    command: ['--network', 'custom', '--chain-id', '${CHAIN_ID}', '--feeder-gateway-url', '${FEEDER_GATEWAY_URL}', '--gateway-url', '${GATEWAY_URL}', '--storage.state-tries', 'archive', '--data-directory', './pathfinder-db']
